[debug]
disableExecutionOperations = true

[global]
loggingConfig = "logging.conf"

[logging]
metrics = false

[mainWindow]
title = "Phobos"
minimumSize = { width = 480, height = 360 }
defaultSize = { width = 1024, height = 600 }

[photoSet]
minimumPhotosInSeries = 3
allowedSecondDriftInSeries = 1.1

[imageLoaderThread]
processingSize = [1920, 1080]
noiseMedianSize = 3

[photoItemWidget.focusIcon]
padding = 7
opacity = 0.5
color = "orange"
sizePercent = 0.15
path = ":icons/focus.png"

[photoItemWidget.qualityText]
padding = 7
opacity = 1.0
decimalPlaces = 2
color = "red"
font = { family = "Courier", pointSize = 10, weight = 75 }

[photoItemWidget.bestMarkIcon]
path = ":icons/star.png"
opacity = 0.5
color = "yellow"
sizePercent = 0.2
padding = 7

[photoItemWidget.ordNum]
size = 20
font = { family = "Courier", pointSize = 12, weight = 75, color = "black", opacity = 1.0 }
background = { type = "square", color = "red", opacity = 0.5 } # type circle is possible
bestBackground = { type = "square", color = "green", opacity = 0.5 }

[photoItemWidget.border]
width = 3

[photoItemWidget.histogram]
width = 128
height = 64
fillColor = "transparent"
value = { style = "fill", color = "#CC9900", opacity = 0.8 }
red = { style = "line", color = "red", opacity = 0.4 }
green = { style = "line", color = "limegreen", opacity = 0.4 }
blue = { style = "line", color = "#0939FF", opacity = 0.4 }

[category.unknown]
color = "darkGray"
icon = ":icons/awesome/png/question-mark-on-a-circular-black-background.png"

[category.selected]
color = "green"
icon = ":icons/awesome/png/checked-symbol.png"

[category.discarded]
color = "red"
icon = ":icons/awesome/png/cross-mark-on-a-black-circle-background.png"

[allSeriesView]
seriesSpacing = 10
photosSpacing = 2
enabledAddons = ["focus", "best", "score"]

[seriesView]
enabledAddons = ["focus", "best", "score", "histogram", "ord"]

[seriesView.num]
visibleItems = 2
default = true

[navigationBar]
allSeriesIcon = ":icons/all_grid.png"
numSeriesIcon = ":icons/num_grid.png"
oneSeriesIcon = ":icons/scroll_grid.png"
iconColor = "blue"
spacing = 2
buttonSize = [40, 40]
buttonMargin = 4

[imageCache]
preloadSize = { width = 320, height = 240 }
fullSize = { width = 1920, height = 1080 }
fullMaxBytes = 1000000000

[operation]
delete = { color = "red", icon = ":icons/awesome/png/trash.png" }
move = { color = "darkorange", icon = ":icons/awesome/png/move-document.png" }
copy = { color = "blue", icon = ":icons/awesome/png/copy-document.png" }
rename = { color = "green", icon = ":icons/awesome/png/pencil.png" }

