[debug]
disableExecutionOperations = true

[logging]
config = "logging.conf"
metrics = false
enhancements = true

[mainWindow]
title = "Phobos"
minimumSize = { width = 480, height = 360 }
defaultSize = { width = 1024, height = 600 }

[fullscreenWindow]
defaultSize = [1024, 768]

[photoSet]
minimumPhotosInSeries = 3
allowedSecondDriftInSeries = 2.0
maximumTimeBetweenTwoPhotosInSeries = 3.0

[metricCalculator]
processingSize = [800, 800]
blurAlgorithm = "laplace" # laplace/laplaceMod/sobel
blurRoiSide = 5
noiseMedianSize = 3

[metricWeights]
blur = 1
noise = 0
contrast = 1
sharpness = 1
depthOfField = 1
saturation = 1
complementary = 1

[photoItemWidget.focusIcon]
enabled = true
padding = 7
opacity = 0.5
color = "orange"
sizePercent = 0.15
minSize = [20, 20]
maxSize = [80, 80]
icon = ":icons/focus.png"

[photoItemWidget.focusBorder]
enabled = true
color = "orange"
width = 2
bottomOnly = true

[photoItemWidget.qualityText]
padding = 7
opacity = 1.0
decimalPlaces = 2
color = "red"
font = { family = "Courier", pointSize = 10, weight = 75 }

[photoItemWidget.bestMarkIcon]
icon = ":icons/awesome/png/star.png"
opacity = 0.5
color = "yellow"
sizePercent = 0.2
minSize = [20, 20]
maxSize = [80, 80]
padding = 7

[photoItemWidget.ordNum]
size = 20
font = { family = "Courier", pointSize = 12, weight = 75, color = "black", opacity = 1.0 }
background = { type = "square", color = "red", opacity = 0.5 } # type circle is possible
bestBackground = { type = "square", color = "green", opacity = 0.5 }

[photoItemWidget.border]
width = 5

[photoItemWidget.histogram]
size = [128, 64]
minWidgetSize = [256, 128]
fillColor = "transparent"
padding = 7
value = { style = "fill", color = "#CC9900", opacity = 0.8 }
red = { style = "line", color = "red", opacity = 0.4 }
green = { style = "line", color = "limegreen", opacity = 0.4 }
blue = { style = "line", color = "#0939FF", opacity = 0.4 }

[detailsDialog.image]
size = [150, 100]

[detailsDialog.histogram]
size = [128, 64]
fillColor = "transparent"
value = { style = "fill", color = "#CC9900", opacity = 1 }
red = { style = "line", color = "red", opacity = 0.8 }
green = { style = "line", color = "limegreen", opacity = 0.8 }
blue = { style = "line", color = "#0939FF", opacity = 0.8 }

[detailsDialog.hueDisplay]
size = [128, 64]
fillColor = "transparent"
barSpacing = 3

[detailsDialog.cumulativeHistogram]
size = [128, 64]
fillColor = "transparent"
value = { style = "fill", color = "#CC9900", opacity = 1 }
red = { style = "line", color = "red", opacity = 0.8 }
green = { style = "line", color = "limegreen", opacity = 0.8 }
blue = { style = "line", color = "#0939FF", opacity = 0.8 }

[category.unknown]
color = "darkGray"
icon = ":icons/awesome/png/question-mark-on-a-circular-black-background.png"

[category.selected]
color = "#8cff66"
icon = ":icons/awesome/png/checked-symbol.png"

[welcomeView]
toolbarSupport = ["file", "help"]

[allSeriesView]
seriesSpacing = 10
photosSpacing = 2
maxPhotoHeight = 400
enabledAddons = ["focus", "best", "score"]
toolbarSupport = ["file", "view", "select", "process", "help"]

[seriesView]
enabledAddons = ["focus", "best", "score", "histogram", "ord"]

[seriesView.num]
visibleItems = 2
default = true
toolbarSupport = ["file", "view", "series", "select", "process", "help"]

[seriesView.row]
toolbarSupport = ["file", "view", "series", "select", "process", "help"]

[laboratoryView]
toolbarSupport = ["view", "series", "enhance", "help"]

[navigationBar.icon]
fileImport = { icon = ":icons/awesome/png/open-folder.png", color="orange" }

viewAllSeries = { icon = ":icons/all_grid.png", color = "#006FE8" }
viewSingleSeries = { icon = ":icons/num_grid.png", color = "#006FE8" }
viewScrollable = { icon = ":icons/scroll_grid.png", color = "#006FE8" }
viewFullscreenPreview = { icon = ":icons/preview_window.png", color = "#006FE8" }
viewLaboratory = { icon = ":icons/awesome/png/beaker.png", color = "purple" }
viewPhotoDetails = { icon = ":icons/awesome/png/bar-graph-on-a-rectangle.png", color = "#22c036" }

seriesPrevious = { icon = ":icons/awesome/png/left-arrow.png", color = "#006FE8" }
seriesNext = { icon = ":icons/awesome/png/arrowhead-pointing-to-the-right.png", color = "#006FE8" }

selectBest = { icon = ":icons/awesome/png/star.png", color="#fce700" }
selectInvert = { icon = ":icons/awesome/png/couple-of-arrows-changing-places.png", color="red" }
selectAll = { icon=":icons/awesome/png/check.png", color="red" }
selectClear = { icon=":icons/awesome/png/undo-arrow.png", color="red" }

processMove = { icon = ":icons/awesome/png/move-document.png", color = "darkorange" } 
processDelete = { icon = ":icons/awesome/png/trash.png", color = "red" }
processRename = { icon = ":icons/awesome/png/pencil.png", color = "green" }
processCopy = { icon = ":icons/awesome/png/copy-document.png", color = "blue" }

helpLicense = { icon=":icons/awesome/png/text-file.png", color="black" }

hideNavigation = { icon = ":icons/awesome/png/chevron-arrow-up.png", color = "gray" }
showNavigation = { icon = ":icons/awesome/png/chevron-arrow-down.png", color = "gray" }

[navigationBar.config]
buttonSize = [34, 34]
inlineButtonSize = [15, 15]
hideButtonSize = [10, 10]
spacing = 1
separatorMargin = 0
minimumHeight = 83

[statusBar.slider]
plusButton = { icon = ":icons/awesome/png/plus-black-symbol.png", color = "red", iconSize = [10,10], size = [15,15] }
minusButton = { icon = ":icons/awesome/png/minus-symbol.png", color = "red", iconSize = [10,10], size = [15,15]  }
sliderSize = { width = 150, height = 15 }
sliderStyle = "QSlider::groove:horizontal{border:0;height:2px;background:gray;margin:0;} QSlider::handle:horizontal{border:0;width:5px;background:darkgray;margin:-6px 0;}"

[statusBar.leftRightNav]
leftButton = { icon = ":icons/awesome/png/chevron-pointing-to-the-left.png", color = "red", iconSize = [10,10], size = [15,15] }
rightButton = { icon = ":icons/awesome/png/right-chevron.png", color = "red", iconSize = [10,10], size = [15,15] }

[imageCache]
preloadSize = { width = 320, height = 240 }
fullSize = { width = 1920, height = 1080 }
fullMaxBytes = "100M"

[operation]
delete = { color = "red", icon = ":icons/awesome/png/trash.png" }
move = { color = "darkorange", icon = ":icons/awesome/png/move-document.png" }
copy = { color = "blue", icon = ":icons/awesome/png/copy-document.png" }
rename = { color = "green", icon = ":icons/awesome/png/pencil.png" }

