[global]
loggingConfig = "logging.conf"

[logging]
metrics = false

[mainWindow]
title = "Phobos"
minimumSize = { width = 480, height = 360 }
defaultSize = { width = 1024, height = 600 }

[photoSet]
seriesTimeThreshold = 2

[imageLoaderThread]
processingSize = [1920, 1080]
noiseMedianSize = 3

[photoItem]
pixmapSize = { width = 320, height = 240 }

[photoItemWidget.focusIcon]
padding = 7
opacity = 0.5
color = "orange"
sizePercent = 0.15
path = ":icons/focus.png"

[photoItemWidget.qualityText]
padding = 7
opacity = 1.0
decimalPlaces = 2
color = "red"
font = { family = "Courier", pointSize = 10, weight = 75 }

[photoItemWidget.bestMarkIcon]
path = ":icons/star.png"
opacity = 0.5
color = "yellow"
sizePercent = 0.2
padding = 7

[photoItemWidget.ordNum]
size = 20
font = { family = "Courier", pointSize = 12, weight = 75, color = "black", opacity = 1.0 }
background = { type = "square", color = "red", opacity = 0.5 } # type circle is possible

[photoItemWidget.border]
width = 2
colorUnknown = "darkGray"
colorSelected = "green"
colorDiscarded = "red"

[photoItemWidget.histogram]
width = 128
height = 64
opacity = 0.6
color = "red"
fillColor = "transparent"

[allSeriesView]
seriesSpacing = 15
photosSpacing = 3
pixmapSize = { width = 320, height = 240 } # should be the same as photoItem.pixmapSize
enabledAddons = ["focus", "best", "score"]

[seriesView]
maxPixmapSize = { width = 1920, height = 1080 }
enabledAddons = ["focus", "best", "score", "histogram", "ord"]

[seriesView.num]
visibleItems = 2
default = true

[navigationBar]
allSeriesIcon = ":icons/all_grid.png"
numSeriesIcon = ":icons/num_grid.png"
oneSeriesIcon = ":icons/scroll_grid.png"
iconColor = "blue"
spacing = 2
buttonSize = [40, 40]
buttonMargin = 4

