[debug]
disableExecutionOperations = true

[logging]
config = "logging.conf"
metrics = false

[mainWindow]
title = "Phobos"
minimumSize = { width = 480, height = 360 }
defaultSize = { width = 1024, height = 600 }

[photoSet]
minimumPhotosInSeries = 3
allowedSecondDriftInSeries = 2.0
maximumTimeBetweenTwoPhotosInSeries = 3.0

[metricCalculator]
processingSize = [800, 800]
blurAlgorithm = "laplace" # laplace/laplaceMod/sobel
blurRoiSide = 5
noiseMedianSize = 3

[metricWeights]
blur = 1
noise = 0
contrast = 1
sharpness = 1
depthOfField = 1
saturation = 1
complementary = 1

[photoItemWidget.focusIcon]
enabled = true
padding = 7
opacity = 0.5
color = "orange"
sizePercent = 0.15
minSize = [20, 20]
maxSize = [80, 80]
path = ":icons/focus.png"

[photoItemWidget.focusBorder]
enabled = true
color = "orange"
width = 3

[photoItemWidget.qualityText]
padding = 7
opacity = 1.0
decimalPlaces = 2
color = "red"
font = { family = "Courier", pointSize = 10, weight = 75 }

[photoItemWidget.bestMarkIcon]
path = ":icons/star.png"
opacity = 0.5
color = "yellow"
sizePercent = 0.2
minSize = [20, 20]
maxSize = [80, 80]
padding = 7

[photoItemWidget.ordNum]
size = 20
font = { family = "Courier", pointSize = 12, weight = 75, color = "black", opacity = 1.0 }
background = { type = "square", color = "red", opacity = 0.5 } # type circle is possible
bestBackground = { type = "square", color = "green", opacity = 0.5 }

[photoItemWidget.border]
width = 5

[photoItemWidget.histogram]
size = [128, 64]
minWidgetSize = [256, 128]
fillColor = "transparent"
padding = 7
value = { style = "fill", color = "#CC9900", opacity = 0.8 }
red = { style = "line", color = "red", opacity = 0.4 }
green = { style = "line", color = "limegreen", opacity = 0.4 }
blue = { style = "line", color = "#0939FF", opacity = 0.4 }

[detailsDialog.image]
size = [150, 100]

[detailsDialog.histogram]
size = [128, 64]
fillColor = "transparent"
value = { style = "fill", color = "#CC9900", opacity = 1 }
red = { style = "line", color = "red", opacity = 0.8 }
green = { style = "line", color = "limegreen", opacity = 0.8 }
blue = { style = "line", color = "#0939FF", opacity = 0.8 }

[detailsDialog.hueDisplay]
size = [128, 64]
fillColor = "transparent"
barSpacing = 3

[detailsDialog.cumulativeHistogram]
size = [128, 64]
fillColor = "transparent"
value = { style = "fill", color = "#CC9900", opacity = 1 }
red = { style = "line", color = "red", opacity = 0.8 }
green = { style = "line", color = "limegreen", opacity = 0.8 }
blue = { style = "line", color = "#0939FF", opacity = 0.8 }

[category.unknown]
color = "darkGray"
icon = ":icons/awesome/png/question-mark-on-a-circular-black-background.png"

[category.selected]
color = "#8cff66"
icon = ":icons/awesome/png/checked-symbol.png"

[allSeriesView]
seriesSpacing = 10
photosSpacing = 2
maxPhotoHeight = 400
enabledAddons = ["focus", "best", "score"]

[seriesView]
enabledAddons = ["focus", "best", "score", "histogram", "ord"]

[seriesView.num]
visibleItems = 2
default = true

[navigationBar]
allSeries = { icon = ":icons/all_grid.png", color = "#006FE8", margin = 4 }
numSeries = { icon = ":icons/num_grid.png", color = "#006FE8", margin = 4 }
oneSeries = { icon = ":icons/scroll_grid.png", color = "#006FE8", margin = 4 }
singlePhoto = { icon = ":icons/preview_window.png", color = "#006FE8", margin = 4 }
prevSeries = { icon = ":icons/awesome/png/left-arrow.png", color = "#006FE8" }
nextSeries = { icon = ":icons/awesome/png/arrowhead-pointing-to-the-right.png", color = "#006FE8" }
prevItem =  { icon = ":icons/awesome/png/chevron-pointing-to-the-left.png", color = "#006FE8" }
nextItem = { icon = ":icons/awesome/png/right-chevron.png", color = "#006FE8" }
movePhotos = { icon = ":icons/awesome/png/move-document.png", color = "darkorange" } 
deletePhotos = { icon = ":icons/awesome/png/trash.png", color = "red" }
openFolder = { icon = ":icons/awesome/png/open-folder.png", color="orange" }
selectBest = { icon = ":icons/star.png", color="yellow" }
spacing = 2
buttonSize = [48, 48]
buttonMargin = 10

[imageCache]
preloadSize = { width = 320, height = 240 }
fullSize = { width = 1920, height = 1080 }
fullMaxBytes = "100M"

[operation]
delete = { color = "red", icon = ":icons/awesome/png/trash.png" }
move = { color = "darkorange", icon = ":icons/awesome/png/move-document.png" }
copy = { color = "blue", icon = ":icons/awesome/png/copy-document.png" }
rename = { color = "green", icon = ":icons/awesome/png/pencil.png" }

